# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: api-1.0.$(Build.BuildId)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
    - '*.yml'

pool:
  name: student-lab-pool

variables:
  - name: artifactName
    value: 'api'

steps:
- script: |
    echo "Packaging api app..."
    mkdir $(Build.ArtifactStagingDirectory)/package
    cp application.py $(Build.ArtifactStagingDirectory)/package/
    cp requirements.txt $(Build.ArtifactStagingDirectory)/package/
  displayName: 'Package api Files'
  condition: and(succeeded(), ne(variables['skip_build'], 'true'))

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/package'
    artifact: '$(artifactName)'
    publishLocation: 'pipeline'
  displayName: 'Publish api Pipeline Artifact'
  condition: and(succeeded(), ne(variables['skip_build'], 'true'))
